#pragma once

// define tương ứng ani trong data

//MARIO animation

//Small mario 
#define ID_ANI_SMALL_MARIO_IDLE_RIGHT	100
#define ID_ANI_SMALL_MARIO_IDLE_LEFT	101
#define ID_ANI_SMALL_MARIO_WALK_RIGHT	102
#define ID_ANI_SMALL_MARIO_WALK_LEFT	103
#define ID_ANI_SMALL_MARIO_JUMP_RIGHT	104
#define ID_ANI_SMALL_MARIO_JUMP_LEFT	105
#define ID_ANI_SMALL_MARIO_SKID_RIGHT	106
#define ID_ANI_SMALL_MARIO_SKID_LEFT	107
#define ID_ANI_SMALL_MARIO_RUN_RIGHT	108
#define ID_ANI_SMALL_MARIO_RUN_LEFT		109
#define ID_ANI_SMALL_MARIO_DIE			110

//Big mario
#define ID_ANI_BIG_MARIO_IDLE_RIGHT			200
#define ID_ANI_BIG_MARIO_IDLE_LEFT			201
#define ID_ANI_BIG_MARIO_WALK_RIGHT			202
#define ID_ANI_BIG_MARIO_WALK_LEFT			203
#define ID_ANI_BIG_MARIO_JUMP_RIGHT			204
#define ID_ANI_BIG_MARIO_JUMP_LEFT			205
#define ID_ANI_BIG_MARIO_SKID_RIGHT			206
#define ID_ANI_BIG_MARIO_SKID_LEFT			207
#define ID_ANI_BIG_MARIO_CROUCH_RIGHT		208
#define ID_ANI_BIG_MARIO_CROUCH_LEFT		209
#define ID_ANI_BIG_MARIO_RUN_RIGHT			210
#define ID_ANI_BIG_MARIO_RUN_LEFT			211
#define ID_ANI_BIG_MARIO_KICK_RIGHT			212
#define ID_ANI_BIG_MARIO_KICK_LEFT			213

//Fire mario
#define ID_ANI_FIRE_MARIO_IDLE_RIGHT		300
#define ID_ANI_FIRE_MARIO_IDLE_LEFT			301
#define ID_ANI_FIRE_MARIO_WALK_RIGHT		302
#define ID_ANI_FIRE_MARIO_WALK_LEFT			303
#define ID_ANI_FIRE_MARIO_JUMP_RIGHT		304
#define ID_ANI_FIRE_MARIO_JUMP_LEFT			305
#define ID_ANI_FIRE_MARIO_SKID_RIGHT		306
#define ID_ANI_FIRE_MARIO_SKID_LEFT			307
#define ID_ANI_FIRE_MARIO_CROUCH_RIGHT		308
#define ID_ANI_FIRE_MARIO_CROUCH_LEFT		309
#define ID_ANI_FIRE_MARIO_RUN_RIGHT			310
#define ID_ANI_FIRE_MARIO_RUN_LEFT			311
#define ID_ANI_FIRE_MARIO_KICK_RIGHT		312
#define ID_ANI_FIRE_MARIO_KICK_LEFT			313
#define ID_ANI_FIRE_MARIO_ATTACK_RIGHT		314
#define ID_ANI_FIRE_MARIO_ATTACK_LEFT		315

//Racoon mario
#define ID_ANI_RACOON_MARIO_IDLE_RIGHT			400
#define ID_ANI_RACOON_MARIO_IDLE_LEFT			401
#define ID_ANI_RACOON_MARIO_WALK_RIGHT			402
#define ID_ANI_RACOON_MARIO_WALK_LEFT			403
#define ID_ANI_RACOON_MARIO_JUMP_RIGHT			404
#define ID_ANI_RACOON_MARIO_JUMP_LEFT			405
#define ID_ANI_RACOON_MARIO_SKID_RIGHT			406
#define ID_ANI_RACOON_MARIO_SKID_LEFT			407
#define ID_ANI_RACOON_MARIO_CROUND_RIGHT		408
#define ID_ANI_RACOON_MARIO_CROUND_LEFT			409
#define ID_ANI_RACOON_MARIO_RUN_RIGHT			410
#define ID_ANI_RACOON_MARIO_RUN_LEFT			411
#define ID_ANI_RACOON_MARIO_KICK_RIGHT			412
#define ID_ANI_RACOON_MARIO_KICK_LEFT			413
#define ID_ANI_RACOON_MARIO_ATTACK_RIGHT		414
#define ID_ANI_RACOON_MARIO_ATTACK_LEFT			415