#pragma once

// define animation ID 

//MARIO animation

//Small mario 
#define ID_ANI_SMALL_MARIO_IDLE			100
#define ID_ANI_SMALL_MARIO_WALK			101
#define ID_ANI_SMALL_MARIO_SKID			102
#define ID_ANI_SMALL_MARIO_JUMP			103
#define ID_ANI_SMALL_MARIO_RUN			104
#define ID_ANI_SMALL_MARIO_JUMP_MAX		105
#define ID_ANI_SMALL_MARIO_WARP			106
#define ID_ANI_SMALL_MARIO_DIE			107
#define ID_ANI_SMALL_MARIO_IDLE_HOLD	108
#define ID_ANI_SMALL_MARIO_RUN_HOLD		109
#define ID_ANI_SMALL_MARIO_KICK			110


//Big mario
#define ID_ANI_BIG_MARIO_IDLE			200
#define ID_ANI_BIG_MARIO_WALK			201
#define ID_ANI_BIG_MARIO_SKID			202
#define ID_ANI_BIG_MARIO_JUMP			203
#define ID_ANI_BIG_MARIO_RUN			204
#define ID_ANI_BIG_MARIO_JUMP_MAX		205
#define ID_ANI_BIG_MARIO_CROUCH			206
#define ID_ANI_BIG_MARIO_WARP			207
#define ID_ANI_BIG_MARIO_IDLE_HOLD		208
#define ID_ANI_BIG_MARIO_RUN_HOLD		209
#define ID_ANI_BIG_MARIO_KICK			210
#define ID_ANI_BIG_MARIO_FALL			211

//Fire mario
#define ID_ANI_FIRE_MARIO_IDLE			300
#define ID_ANI_FIRE_MARIO_WALK			301
#define ID_ANI_FIRE_MARIO_SKID			302
#define ID_ANI_FIRE_MARIO_JUMP			303
#define ID_ANI_FIRE_MARIO_RUN			304
#define ID_ANI_FIRE_MARIO_JUMP_MAX		305
#define ID_ANI_FIRE_MARIO_CROUCH		306
#define ID_ANI_FIRE_MARIO_WARP			307
#define ID_ANI_FIRE_MARIO_IDLE_HOLD		308
#define ID_ANI_FIRE_MARIO_RUN_HOLD		309
#define ID_ANI_FIRE_MARIO_KICK			310
#define ID_ANI_FIRE_MARIO_ATTACK		311
#define ID_ANI_FIRE_MARIO_FALL			312

//Racoon mario
#define ID_ANI_RACCOON_MARIO_IDLE			400
#define ID_ANI_RACCOON_MARIO_WALK			401
#define ID_ANI_RACCOON_MARIO_SKID			402
#define ID_ANI_RACCOON_MARIO_JUMP			403
#define ID_ANI_RACCOON_MARIO_RUN			404
#define ID_ANI_RACCOON_MARIO_JUMP_MAX		405
#define ID_ANI_RACCOON_MARIO_CROUCH			406
#define ID_ANI_RACCOON_MARIO_WARP			407
#define ID_ANI_RACCOON_MARIO_IDLE_HOLD		408
#define ID_ANI_RACCOON_MARIO_RUN_HOLD		409
#define ID_ANI_RACCOON_MARIO_KICK			410
#define ID_ANI_RACCOON_MARIO_ATTACK			411
#define ID_ANI_RACCOON_MARIO_FALL			412
#define ID_ANI_RACCOON_MARIO_FALL_MAX		413
#define	ID_ANI_RACCOON_MARIO_SLOW_FALL		414
#define	ID_ANI_RACCOON_MARIO_FLY			415

//object
#define ID_ANI_FIREBALL	500

#define ID_ANI_GOOMBA_WALK	600
#define ID_ANI_GOOMBA_DIE	601

#define ID_ANI_KOOPAS_WALK			700
#define ID_ANI_KOOPAS_SHELL			701
#define ID_ANI_KOOPAS_SHELL_MOVING	702

#define ID_ANI_QUESTION_BLOCK			800
#define ID_ANI_QUESTION_BLOCK_CLAIMED	801
#define ID_ANI_BRICK			802
#define ID_ANI_MUSIC_NOTE		803
#define ID_ANI_HIDDEN_NOTE		804
#define ID_ANI_MUSHROOM_RED		805
#define ID_ANI_MUSHROOM_GREEN	806
#define ID_ANI_LEAF				807
#define ID_ANI_P_BUTTON			808
#define ID_ANI_P_BUTTON_CLAIMED	809